name: Hourly Inflation Survey

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-survey:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This ensures we have the full history
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyai python-dotenv GoogleNews openpyxl requests

    - name: Pull latest changes
      run: |
        git pull origin main

    - name: Run survey script
      env:
        api_key4: ${{ secrets.API_KEY10 }}
      run: python inflation_survey.py
      
    - name: Commit and push results
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add results_*.xlsx
        git commit -m "Add survey results for $(date +'%Y-%m-%d %H:00')" || exit 0
        git push origin main
