name: Hourly Inflation Survey

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:  # Allows manual trigger

# Add permissions block
permissions:
  contents: write
  actions: write

jobs:
  run-survey:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: true
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openai python-dotenv GoogleNews openpyxl requests

    - name: Run survey script
      env:
        api_key4: ${{ secrets.API_KEY10 }}
      run: python inflation_survey.py
      
    - name: Commit and push results
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add results_*.xlsx
        git commit -m "Add survey results for $(date +'%Y-%m-%d %H:00')" || exit 0
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
